name: FCE Ultra FX Build

on: workflow_disparch

jobs:
  build:
    name: Build FCE Ultra FX
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii", "GameCube"]
    container: devkitpro/devkitppc:20230110

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j2
    
    - name: Copy Wii artifact
      if: ${{ matrix.image == 'Wii' }}
      run: | 
        mkdir -p dist/FCEUltraFX/apps/fceultrafx
        mkdir -p dist/FCEUltraFX/fceultrafx/roms
        mkdir dist/FCEUltraFX/fceultrafx/cheats
        mkdir dist/FCEUltraFX/fceultrafx/saves
        touch dist/FCEUltraFX/fceultrafx/roms/romsdir
        touch dist/FCEUltraFX/fceultrafx/cheats/cheatsdir
        touch dist/FCEUltraFX/fceultrafx/saves/savesdir
        cp hbc/* dist/FCEUltraFX/apps/fceultrafx/
        cp executables/fceultrafx-wii.dol dist/FCEUltraFX/apps/fceultrafx/boot.dol
  
    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with: 
        name: FCEUltraFX
        path: |
         dist/FCEUltraFX/
    
    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j2
        
    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: | 
        mkdir -p dist/FCEUltraFX-GameCube
        cp executables/fceultrafx-gc.dol dist/FCEUltraFX-GameCube/
    
    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'GameCube' }}
      with: 
        name: FCEUltraFX-GameCube
        path: |
         dist/FCEUltraFX-GameCube/
